### ISSUE TITLE
Android

### ISSUE THREAD

**Issue by campones** [TylerZubke/Videojs-AFK-Monitor#1]
Hello

Thanks for your plugin. In fact I have something similar but not so good looking and sophisticated.

var vid1 = videojs('player'); vid1.on("play",function(e){console.log('started!');setTimeout(function() {videojs('player').pause()}, 3600000);

I haven't been able to make your plugin work on android. Is it expected or a bug? Using android 4.0.4

**Comment by TylerZubke** [comment]
Is the device loading the native inline player?  If it is, it won't work since I can't put something over the inline player. What options are you using? If you aren't changing showMessageAfter it's going to take 20 minutes without you touching within the player for it to trigger. Is it possible your screen is going to sleep or you are touching within the player? That will reset the timer.

**Comment by campones** [comment]
I setup 10000 (10s) in the js file for testing purpose. And it never showed up in android with chrome browser, I see the videojs player loading fine. 
my phone is an old xperia but I asked to check on a samsung s6 edge and it is the same.

In the other hand  my little piece of code is working on android too and seems more stable.. I explain: I want the player to stop after one hour and I run some streams in normal chrome desktop and I never saw your plugin loading. When I setup short time for testing, it s fine. When I put one hour.. It just doesn't show up..
And this for me is a much bigger problem than working on android (since I still have my little code as a fallback in case your plugin fails)

**Comment by campones** [comment]
I see this

```
           player.on('useractive', function(){
                `clearVjsTimeout('countdownTimeoutId');
```

Does that means if, for example, I setup 30min and the user hover the player after 20min, it does reset the counter and he get another 30min?

**Comment by TylerZubke** [comment]
That's exactly what it means. I was going to ask if you were aware that the timer reset upon the user hovering over the player. I suppose I could add an option to never reset the countdown even if the user is active if that's what you are looking for. For android you may want to hook the phone up to a debugger and look at it there because as long as it's the videojs player and not the android inline player it should be working. iOS is completely different. I'd recommend not even attaching the plugin if iOS is detected because most of the time the device will default to the native player and the plugin won't work.

**Comment by campones** [comment]
well I d need to check with a proper phone because mine is so slow and network is also so bad I wouldn't be surprised if some scripts weren't loaded properly. 
Yes I was looking to disable the hovering function that reset the countdown but till now, no success

**Comment by campones** [comment]
Well i deleted my message instead of editing.
I would love if you could add that option. For me the user being active on the player doesn't mean he should get a reset of the countdown. 

Also I modified this 

`player.pause().currentTime().trigger('loadstart');
                // player.hasStarted(false);
                player.hasStarted(true);
`
Because I m using the poster setup. Resetting the player to the state before it starts was hiding the control bar. Also the (0) would make the player play the first segment downloaded.. which is not very good if a user only want to pause for a while and then restart a live stream.

**Comment by campones** [comment]
Hello, after so many years I m playing around with your videoJs plugin and I m trying the option we talked about 6 years ago

`ignoreUserActive`  I added this in the global config of the .js file but it doesn't work at all? 

Edit: sorry it does work indeed, I forgot to update your plugin script.. so obviously the directive wasn't working. 
So yea it works, but only if the player entered the vjs-inactive state at some point. if you keep moving the mouse over the screen it will not trigger the pause. But in a real world scenario, that's not relevent, no one is going to keep moving the mouse on a video player, so that's great, thank you for implementing this!

**Comment by campones** [comment]
Actually it took me a while to understand why it seemed to work when setting up a short timer like 20s (20000) for testing purposes and not when setting up a realistic scenario, like 1800000 (30min).  It's because when you interact with the player, when you double click on it to go fullscreen or leave fullscreen for example, then it somehow reset the player state and the script isn't working as expected.
